#!/usr/bin/env ruby

require "yaml"
require "erb"

# generic variables
@config     = YAML.load_file("kubernetes-smilo.yaml")
@nodes      = YAML.load_file("nodes.yaml")["nodes"]

@Permissioned_Nodes_File    = @config["smilo"]["Permissioned_Nodes_File"]
@Genesis_File               = @config["smilo"]["Genesis_File"]

@Blackbox_Config_Dir         = @config["smilo"]["tm"]["Blackbox_Config_Dir"]

@Node_WSPort                = @config["geth"]["Node_WSPort"]
@NodeP2P_ListenAddr         = @config["geth"]["NodeP2P_ListenAddr"]

#####################################################
# Generate genesis.json and permissioned-nodes.json
#####################################################

`mkdir -p out/config`

puts "create genesis files with all discovered keystore accounts pre alloc with funds."

puts(@Genesis_File)
File.open(@Genesis_File, "w") do |f|
  f.puts (ERB.new(File.read("genesis.json.erb"), nil, "-").result)
end

puts "create permission nodes file containing all the nodes."

puts(@Permissioned_Nodes_File)
File.open(@Permissioned_Nodes_File , "w") do |f|
  f.puts (ERB.new(File.read("permissioned-nodes.json.erb"), nil, "-").result)
end

puts "create blackbox config."
puts(@Blackbox_Config_Dir + "/blackbox-config.json")
File.open(@Blackbox_Config_Dir + "/blackbox-config.json" , "w") do |f|
  f.puts (ERB.new(File.read("blackbox-config.json.erb"), nil, "-").result)
end
