#!/usr/bin/env ruby

if File.directory?("out")
  puts("\n The 'out' directory already exist.")
  puts(" Do you want to delete the directory and re-generate it [Y/N]?")
  res = gets
  res = res.upcase.strip
  if not (res == "Y" or res == "YES")
    puts("OK, keeping the 'out' dir, stay safe :)")
    exit
  end
    `rm -r out`
end

`
# create the output directory if
# it doesn't exist
mkdir -p out/config

# generate the nodes.yaml
# file for the set number of
# nodes.
./smilo-create-nodes

# `
# puts ""
# puts "  Generating keys..."
# `
# # generate the keygen script
# # to generate nodekey, account keys, and
# # smilo transaction manger (tm.pub,tm.key) keys.
# ./smilo-keygen
# `

puts "  Generating Smilo configs..."
`
# generate the appropriate config files:
#   permissioned-nodes.json
#   genesis.json 
./smilo-config
`

puts ""
puts  "  Base smilo resources have been generated. "
puts  "  Running ./kubernetes-smilo to generate Kubernetes resources."
puts ""
`
./kubernetes-smilo
`
puts "  Deploy Smilo Kubernetes resources:"
puts "  $> kubectl apply -f out"

